env: "local" # local, dev, prod
dsn: "postgresql://postgres:password@db:5432/shop"
auth:
  private_key: "secret_key"
  expiration_time: "10m"
grpc_server:
  port: 7000
http_server:
  port: 7001
  timeout: "4s"
  idle_timeout: "60s"